# Generated by Django 4.2.1 on 2023-11-03 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
