# Generated by Django 4.2.7 on 2023-11-11 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likeapp', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bookmark_user',
            field=models.ManyToManyField(blank=True, related_name='bookmark_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
